"""reset_for_identity_linking

Revision ID: 879fbc359245
Revises: 002
Create Date: 2026-03-16 11:17:05.429956

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '879fbc359245'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id')
    )
    op.create_index(op.f('ix_account_provider'), 'account', ['provider'], unique=False)
    op.create_index(op.f('ix_account_provider_account_id'), 'account', ['provider_account_id'], unique=False)
    op.create_index(op.f('ix_account_user_id'), 'account', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_user_id'), table_name='account')
    op.drop_index(op.f('ix_account_provider_account_id'), table_name='account')
    op.drop_index(op.f('ix_account_provider'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
